_target_: franka_allegro.deployers.FVINN
data_path: ???

# Directories to change by the user depending on where they saved the data
deployment_dump_dir: ???
image_out_dir: null
image_model_type: temporal_ssl

nn_buffer_size: 50
nn_k: 25
data_representations: ${data_representations}
representation_types: ['image'] # Observations used in the representations
representation_importance: [1] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
demos_to_use:  all

view_num: 3
open_loop: false

dump_deployment_info: false

device: cuda
augmentation_functions:
  _target_: visual_kinesthetics.data.augmentation.eval_augmentations
  mean: [0.4029, 0.4320, 0.4348]
  std: [0.2308, 0.2165, 0.2139]
algo_config:
  _target_: visual_kinesthetics.util.eval.base.load_algorithm
  path: "/data/ben/encoders/46163338_1:algorithm.pair_weight=0.0,machine=greene,top=batch_128_4/"
  model_name: model_30.pt
  device: ${deployer.device}
  return_config: true
index_to_factor_map: ['Aadi Human', 'Background 0', 'Ben Human', 'Blue Tape', 'Drill',
       'Franka Arm', 'Green Screw', 'International Plug',
       'Lab Background 1', 'Lab Background 2', 'Mustard', 'Orange Cup',
       'Plier 1', 'Plier 2', 'Plug Adapter', 'Red Screw', 'Screw Box',
       'US Plug', 'White Plug Adapter', 'Wrench', 'Xela Curved Hand',
       'Yinlong Human']
task_factors: ["Franka Arm", "Xela Curved Hand", "Blue Tape"]